Update to bindgen that doesn't crash
Bindgen would crash with the following error message on SDK version
6.0.22:

  thread 'main' panicked at /Users/niklasdusenlund/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:878:9:
  "enum_(unnamed_at_/opt/DA145xx_SDK/6_0_22_1401/sdk/platform/core_modules/common/api/co_bt_h_1290_1)" is not a valid Ident